title: OK? 
description: Document Analysis Semester Project by Ludmila, Alex and Kascha
show_downloads: True
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - README.md

text-align: justify,
theme: jekyll-theme-hacker
